### ISSUE TITLE
Incorrect information about Total Supply In KRC721 Token contract

### ISSUE THREAD

**Issue by jainuttam185** [p2eengineering/kalp-studio-documentation#5]
The information given about Total Supply in KRC721 Token Contract is not correct. I think it is of tokenURI function
![Screenshot 2024-09-21 232911](https://github.com/user-attachments/assets/e58f268c-1817-4799-a79e-c41c972f2c41)

**Comment by siddheshp2e** [comment]
@jainuttam185 PLease try this implementation right now.


`// ============== ERC721 enumeration extension ===============
// TotalSupply counts non-fungible tokens tracked by this contract.
//
// @param {Context} ctx the transaction context
// @returns {Number} Returns a count of valid non-fungible tokens tracked by this contract,
// where each one of them has an assigned and queryable owner.
 
func (c *TokenERC721Contract) TotalSupply(ctx kalpsdk.TransactionContextInterface) int {
 
    // Check if contract has been intilized first
    initialized, err := checkInitialized(ctx)
    if err != nil {
        panic("failed to check if contract is already initialized:" + err.Error())
    }
    if !initialized {
        panic("Contract options need to be set before calling any function, call Initialize() to initialize contract")
    }
 
    // There is a key record for every non-fungible token in the format of nftPrefix.tokenId.
    // TotalSupply() queries for and counts all records matching nftPrefix.*
 
    iterator, err := ctx.GetStateByPartialCompositeKey(nftPrefix, []string{})
    if err != nil {
        panic("Error creating GetStateByPartialCompositeKey:" + err.Error())
    }
    // Count the number of returned composite keys
 
    totalSupply := 0
    for iterator.HasNext() {
        _, err := iterator.Next()
        if err != nil {
            return 0
        }
        totalSupply++
 
    }
    return totalSupply
 
}`
